---
title: "interation_listcols"
author: "Yuying Lu"
date: "2024-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample = runif(100),
  mat = matrix(1:8, nrow = 2, byrow = TRUE),
  summary = summary(rnorm(100))
)
```


```{r}
l$vec_numeric

l$mat

l$mat[2,3]

l['mat']
l[['mat']]
l[['mat']][2,4]
l[[4]]
```

Make a list that's hopefully a bit more useful

```{r}
list_norm = 
  list(
    a = rnorm(20,0,5),
    b = rnorm(20,4,5),
    c = rnorm(20,0,10),
    d = rnorm(20,4,10)
  )


list_norm[["b"]]

```

Let's reuse the function we used last time

```{r}
mean_and_sd = function(x){
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  return(out_df)
}


mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])

```


## Use a for loop

Creat output list, and run a for loop

```{r}
output = vector("list", length = 4)

for (i in 1:4){
  output[[i]] = mean_and_sd(list_norm[[i]])
}

output
```


## Do the same thing

but with `map` instead


```{r}
map(list_norm, mean_and_sd)
```


```{r}
map(list_norm,mean)
map(list_norm,IQR)
```


```{r}
map_dfr(list_norm,IQR)
map_dbl(list_norm,IQR)
```
```{r}
map_dfr(list_norm,mean_and_sd)
```

### LIST COLUMNS!!!

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm
  )

listcol_df

listcol_df |> 
  filter(name %in% c("a","b"))

listcol_df |> 
  select(-samp)

listcol_df[['samp']][["a"]]
```



```{r}
mean_and_sd(listcol_df[['samp']][["a"]])
```

```{r}
listcol_df[['samp']]
map(listcol_df[['samp']],mean_and_sd)
```
```{r}
df_new = 
  listcol_df |> 
  mutate(output = map(samp, mean_and_sd),
         iqr = map(samp, IQR),
         iqr_dbl = map_dbl(samp, IQR)) |> 
  select(-samp) |> 
  unnest(output)

df_new

```

```{r}
df_new = 
  listcol_df |> 
  mutate(output = map(samp, mean_and_sd),
         iqr = map(samp, IQR),
         iqr_dbl = map_dbl(samp, IQR)) |> 
  unnest(output)

df_new

```

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
data_marj

source("nsduh_table_format.R")


```

```{r}
nsduh_table_format(html= nsduh_html, table_num = 1)
nsduh_table_format(html= nsduh_html, table_num = 4)
nsduh_table_format(html= nsduh_html, table_num = 5)
```


```{r}
nsduh_df = 
  tibble(
    drug = c("marj", "cocaine", "herion"),
    table_n = c(1,4,5)
  ) |> 
  mutate(table = map(table_n, nsduh_table_format ,html = nsduh_html)) |> 
  unnest(table)

nsduh_df
```


```{r}

nsduh_results= 
  tibble(
    name = c("marj", "cocaine", "heroine"),
    number = c(1, 4, 5)) |> 
  mutate(table = map(number, \(num) nsduh_table_format(html = nsduh_html, num))) |> 
  unnest(cols = "table")

nsduh_results
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```


```{r}

weather_nest = 
  weather_df |> 
  nest(data = date:tmin)

weather_nest[["data"]][[1]]
```


# Let's try regression tmax on tmin

```{r}
lm(tmax ~ tmin, data = weather_nest[["data"]][[1]])
```


```{r}
weather_nest |> 
  mutate(
    model_fit = map(data, \(x) lm(tmax ~ tmin, data = x))) |> 
  pull(model_fit)
```


Let's define a function that fits the regression I want

```{r}
weather_lm = function(df){
  lm(tmax~tmin, df)
}
```

```{r}
weather_lm(weather_nest[["data"]][[1]])
```


```{r}
weather_nest |> 
  mutate(model_fit = map(data, weather_lm))
```

```{r}
weather_nest |> 
  mutate(model_fit = map(data, \(x) lm(tmax ~ tmin, data = x)))
```

