---
title: "simulation"
author: "Yuying Lu"
date: "2024-10-31"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```


## writing a simulation function

```{r}
sim_mean_sd = function(sample_size, true_mean = 10, true_sd = 5){
  
  sim_df = 
    tibble(
      x = rnorm(sample_size, true_mean, true_sd)
    )
  out_df = 
    sim_df |> 
    summarise(
      samp_mean = mean(x),
      samp_sd = sd(x)
    )
  return(out_df)
}

sim_mean_sd(sample_size = 3000, true_mean = 4, true_sd = 12)
sim_mean_sd(true_mean = 4, true_sd = 12, sample_size = 3000)
sim_mean_sd(3000, 4, 12)
sim_mean_sd(3000,,4)
sim_mean_sd(3000,4)

```


run this a lot of times


```{r}
sim_mean_sd(30)
```

```{r}
output = vector("list", 1000)

for (i in 1:1000){
  
  output[[i]] = sim_mean_sd(30)
  
}

bind_rows(output) |> 
  summarise(
    ave_samp_mean = mean(samp_mean),
    sd_samp_mean = sd(samp_mean)
  )
```


Can I use map instead?

```{r}
sim_res =  
  tibble(
    iter = 1:1000
  ) |> 
  mutate(samp_res = map(iter, sim_mean_sd, sample_size = 30)) |> 
  unnest(samp_res)
    
sim_res
```

Could I try different sample sizes?

```{r}

# List all possible combinations of (n, iter)
sim_res = 
  expand_grid(
    n = c(10,30,60,100),
    iter = 1:1000
  ) |> 
  mutate(samp_res = map(n, \(x)sim_mean_sd(x, true_mean = 50))) |> 
  unnest(samp_res)

```


```{r}
sim_res |> 
  group_by(n) |> 
  summarize(
    se = sd(samp_mean)
  )
```


```{r}
sim_res |> 
  filter(n == 100) |> 
  ggplot(aes(x = samp_mean)) +
  geom_histogram()
```


```{r}
sim_res |> 
  mutate(
    n = str_c('n = ',n),
    n = fct_inorder(n)) |> 
  ggplot(aes(x = n, y = samp_mean)) +
  geom_violin()
```

#SLR

```{r}
sim_data = 
  tibble(
    x = rnorm(30, mean = 1, sd = 1),
    y = 2 + 3 * x + rnorm(30, 0, 1)
  )

lm_fit = lm(y ~ x, data = sim_data)

sim_data |> 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  stat_smooth(method = "lm")

```

# Turn this into a function

```{r}
sim_regression = function(n){
  sim_data = 
    tibble(
      x = rnorm(n, mean = 1, sd = 1),
      y = 2 + 3 * x + rnorm(n, 0, 1)
    )
  lm_fit = lm(y ~ x, data = sim_data)
  
  out_df = 
    tibble(
      beta0_hat = coef(lm_fit)[1],
      beta1_hat = coef(lm_fit)[2]
    )
  return(out_df)
}


sim_res =
  expand_grid(
    sample_size = c(30, 50, 100),
    iter = 1:1000
  ) |> 
  mutate(lm_res = map(sample_size, \(x)sim_regression(x))) |> 
  unnest(lm_res)

sim_res |> 
  mutate(sample_size = str_c('n = ', sample_size),
         sample_size = fct_inorder(sample_size)) |> 
  ggplot(aes(x = sample_size, y = beta1_hat)) + 
  geom_boxplot()



```


## Birthday problem!!!

Let's put people in a room


```{r}
bdays = sample(1:365, size = 10, replace = TRUE)

length(unique(bdays)) < 10 

```


```{r}
bday_sim = function(n){
  bdays = sample(1:365, size = n, replace = TRUE)
  return(length(unique(bdays)) < n)
}
```

run this a lot

```{r}
sim_res = 
  expand_grid(
    n = c(10, 50),
    iter = 1:1000
  ) |> 
  mutate(res = map_lgl(n, bday_sim)) |> 
  group_by(n) |> 
  summarise(prob = mean(res))
  
sim_res |> 
  ggplot(aes(x = n, y = prob)) +
  geom_line


```


